targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - swaggers2/**
      - swagger_examples/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: true
          with_converter: true
          use_required_attribute_for_headers: true
          ignore_headers: false
          use_default_null_for_lists: false
          use_inheritance: false
          build_only_models: false
          model_postfix: "Dto"
          use_path_for_request_names: true
          include_if_null:
            enabled: true
            value: false
          input_folder: "lib/"
          output_folder: "lib/generated_code/"
          enums_case_sensitive: true
          default_values_map:
            - type_name: int
              default_value: "36"
            - type_name: String
              default_value: ""
          default_header_values_map:
            - header_name: "X-Entitlements-Token"
              default_value: "X-Entitlements-Token"
            - header_name: "X-Cus"
              default_value: "X-Cus"
          response_override_value_map:
            - url: "/v2/commons/availableColours"
              method: get
              overridden_value: "List<Map>"
            - url: "/v2/commons/availableGenres"
              method: get
              overridden_value: "List<GenreV2ResultDto>"
            - url: "/v2/channels"
              method: get
              overridden_value: "List<Channel>"
