name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^4.0.0-nullsafety.1
  
dev_dependencies:
  swagger_dart_code_generator:
    path: ../
  chopper_generator: ^4.0.0-nullsafety.1
  build_runner: 1.12.2
  json_annotation: 4.0.1
  json_serializable: 4.1.1
