name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^4.0.1
  
dev_dependencies:
  swagger_dart_code_generator:
    path: ../
  chopper_generator: any
  build_runner: any
  json_annotation: any
  json_serializable: any
